language: python
python:
  - "3.9"
install:
  - pip install -r requirements.txt
before_script:
  - python manage.py migrate
script:
  - flake8 .
  - python manage.py test
env:
  - DJANGO_SECRET_KEY=django
  - EMAIL_HOST_PASSWORD=gwr
  - DJANGO_ENV=dev